export const LOAD_WEB3_SUCCESS = 'LOAD_WEB3_SUCCESS';
export const LOAD_WEB3_FAIL = 'LOAD_WEB3_FAIL';
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = 'LOAD_BLOCKCHAIN_DATA_SUCCESS';
export const LOAD_BLOCKCHAIN_DATA_FAIL = 'LOAD_BLOCKCHAIN_DATA_FAIL';


export const LOAD_TETHER_SUCCESS = 'LOAD_TETHER_SUCCESS';
export const LOAD_TETHER_FAIL = 'LOAD_TETHER_FAIL';
export const LOAD_TETHER_BALANCE_SUCCESS = 'LOAD_TETHER_BALANCE_SUCCESS';
export const LOAD_TETHER_BALANCE_FAIL = 'LOAD_TETHER_BALANCE_FAIL';

export const LOAD_URIDIUM_SUCCESS = 'LOAD_URIDIUM_SUCCESS';
export const LOAD_URIDIUM_FAIL = 'LOAD_URIDIUM_FAIL';
export const LOAD_URIDIUM_BALANCE_SUCCESS = 'LOAD_URIDIUM_BALANCE_SUCCESS';
export const LOAD_URIDIUM_BALANCE_FAIL = 'LOAD_URIDIUM_BALANCE_FAIL';

export const LOAD_BANK_SUCCESS = 'LOAD_BANK_SUCCESS';
export const LOAD_BANK_FAIL = 'LOAD_BANK_FAIL';
export const LOAD_BANK_BALANCE_SUCCESS = 'LOAD_BANK_BALANCE_SUCCESS';
export const LOAD_BANK_BALANCE_FAIL = 'LOAD_BANK_BALANCE_FAIL';

export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS';
export const SET_LOADING_FAIL = 'SET_LOADING_FAIL';
